### ISSUE TITLE
Axum turbo example not working

### ISSUE THREAD

**Issue by francisstephan** [shuttle-hq/shuttle-examples#184]
When I try to run the Axum Turso example, I get the error:
error[E0277]: the trait bound `TursoOutput: IntoResource<libsql::Database>` is not satisfied
    |
15 | #[shuttle_runtime::main]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoResource<libsql::Database>` is not implemented for `TursoOutput`
   |
   = help: the trait `IntoResource<libsql::database::Database>` is implemented for `TursoOutput`
   = help: for that trait implementation, expected `libsql::database::Database`, found `libsql::Database`
   = note: this error originates in the attribute macro `shuttle_runtime::main` (in Nightly builds, run with -Z macro-backtrace for more info)

However, I used libsql 0.5.0; When I switch back to libsql version 0.3.1 as in your example, it works, so this is definitely a Turso libsql issue

**Comment by jonaro00** [comment]
For me it works:
```sh
$ cd axum/turso # on main branch
$ cargo shuttle run
# ...build...
    Starting turso-example on http://127.0.0.1:8000
2024-08-19T18:10:30.133+02:00 [Runtime] Starting on 127.0.0.1:8000
```

Are you sure you are running it without modifying the `libsql` version (0.3.1)? (I see that libsql 0.5.0 is out. A PR for updating it is welcome.)

**Comment by jonaro00** [comment]
Great! If you want to contribute an upgrade to 0.5, you can look for shuttle-turso in the main shuttle repo.
