### ISSUE TITLE
Qdrant example requires local docker.

### ISSUE THREAD

**Issue by vnermolaev** [shuttle-hq/shuttle-examples#185]
Hi there, I am really enjoying using Shuttle, however I am running in the following issue.

The example found [here](https://github.com/shuttle-hq/shuttle-examples/tree/main/axum/qdrant) runs a local instance of Qdrant, regardless of whether a local (Docker) or cloud instance is specified in `Secrets/toml`.

If Docker is not running, the following error occurs:
```
Error while starting service: Failed to start Docker container. Make sure that a Docker engine is running.

Caused by:
    status: Internal, message: "error trying to connect: No such file or directory (os error 2)", details: [], metadata: MetadataMap { headers: {} }
```

However, I can bypass this issue by directly constructing a client with `qdrant_client:Qdrant` and communicating with it without relying on Docker.

My expectation is that Shuttle would not start the docker by itself.

**Comment by jonaro00** [comment]
Providing the `local_addr` parameter will disable running a local instance on a local run. Docs: https://docs.shuttle.rs/resources/shuttle-qdrant

**Comment by vnermolaev** [comment]
See [PR #294](https://github.com/shuttle-hq/shuttle-docs/pull/294)
