### ISSUE TITLE
"FATAL:  role "root" does not exist" in Postgres container

### ISSUE THREAD

**Issue by min2sia** [shuttle-hq/shuttle-examples#77]
Hello,
I was trying the "SaaS Starter Template", as described in https://docs.shuttle.rs/fullstack/saas-template
on macOS Ventura, M2 chip.
Following sequence worked (just need to run "npm i" to install dependencies before start):
```
npm run shuttle-login
npm run start
npm run deploy
```

However, trying to start local instance failed:
```
npm run dev
...
[next] event - compiled successfully in 55 ms (140 modules)
           [11 Pulling from library/postgres]
           Digest: sha256:5d2aa4a7b5f9bdadeddcf87cf7f90a176737a02a30
           Status: Image is up to date for postgres:11
[ shuttle] 2023-07-31T11:38:41.593779Z ERROR cargo_shuttle: failed to load your service error="Custom error: failed to provision shuttle_shared_db :: Postgres"
[ shuttle] cargo shuttle run --working-directory ./backend/ exited with code 1
--> Sending SIGTERM to other processes..
```
Examining Postgres Docker container log revealed this:
```
2023-07-31 14:38:41 waiting for server to start....2023-07-31 11:38:41.547 UTC [55] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-07-31 14:38:41 2023-07-31 11:38:41.565 UTC [58] LOG:  database system was shut down at 2023-07-31 11:38:41 UTC
2023-07-31 14:38:41 2023-07-31 11:38:41.569 UTC [55] LOG:  database system is ready to accept connections
2023-07-31 14:38:41 2023-07-31 11:38:41.586 UTC [71] FATAL:  role "root" does not exist
```
Looks like this issue could be resolved by setting environment variable POSTGRES_USER to "postgres", but where to do that? Tried setting env variable on my host machine and .env file in project root, but that made no difference.

**Comment by joshua-mo-143** [comment]
Hey! Thanks for sending this issue in - apologies for the extremely overdue response, this should've really been responded to sooner.

Are you using the default Docker configuration?

**Comment by min2sia** [comment]
Thanks for the hint! I wiped docker config files from `~/.docker/`, reinstalled docker and it works now :)

**Comment by joshua-mo-143** [comment]
No worries, happy to help!
